---
static_resources:
  listeners:
    - name: mysql_listener
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 9000
      filter_chains:
          filters:
          - name: envoy.tcp_proxy
            config:
              stat_prefix: msyql_cluster_stats
              cluster: mysql_cluster

  clusters:
    - name: mysql_cluster
      connect_timeout: 1s
      type: strict_dns
      hosts:
        - socket_address:
            address: 0.0.0.0
            port_value: 3306

